### ISSUE TITLE
Broken exim4-config on debian jessie

### ISSUE THREAD

**Issue by Udera** [vexim/vexim2#81] opened 2015-10-11 20:29 UTC
I tried to set up a new mail server on debian jessie. Unfortunately, there is still the string expansion problem in the headers_remove statements, like reported here:
http://www.gossamer-threads.com/lists/exim/users/100446

ref in our code:
https://github.com/vexim/vexim2/blob/master/docs/configure#L665-L676

related bug: https://bugs.exim.org/show_bug.cgi?id=1533
but this fix doesn't seem to be in the debian-jessie packages (neither in the testing).

So it makes vexim unusable for debian jessie at the moment.

**Comment by Z3po** [comment] 2015-10-11 20:41
Well..the "bugfix" doesn't seem to be a bugfix...


    (after taking this discussion to a different forum)
    
    It turns out that the issue was not this bug but a side-effect of the
    implementation of bug 337 - which required list elements to be expanded
    separately rather than the string being expanded and then interpreted
    as a list.
    
    This means that an expansion with one or more (constant) result strings,
    which are the header lists, are no longer tenable.  Alternatives are
    to use multiple headers_remove options on the router, each with a single
    header name - or, in some uses, multiple routers with conditions.

That sounds bad. I'll try setting up a Jessy installation by myself the next days to see if we can do anything to that...

**Comment by Udera** [comment] 2015-10-11 20:45
Ok, I got a working version on jessie. There seems to be a bracket `}` missing. I don't see why but it (seems to) works like this:
````
  headers_remove = ${if or { { <{$spam_score_int}{1} } \
                             { <{$spam_score_int}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                               where localpart = '${quote_mysql::$local_part}' \
                               and domain = '${quote_mysql::$domain}' \
                               and users.on_spamassassin = 1 \
                               and users.domain_id=domains.domain_id}{$value}fail}} } \
                             { eq {0}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                               where localpart = '${quote_mysql::$local_part}' \
                               and domain = '${quote_mysql::$domain}' \
                               and users.on_spamassassin = 0 \
                               and users.domain_id=domains.domain_id}{$value}fail}}} \
                           }} {X-Spam-Score:X-Spam-Report} }
````
added closing bracket in the beginning of the last line.

**Comment by rimas-kudelis** [comment] 2015-10-12 06:33
If you calculate the brackets now, I think the number doesn't match, but it did match previously.

**Comment by Udera** [comment] 2015-10-12 07:48
That is true and this is the reason I don't understand why it works. If you take the original version and start exim in debug mode, it says that there is a missing `}`. That is the reason, I added another `}`.

@rimas-kudelis : Did you test the router after you added the double colons?

**Comment by rimas-kudelis** [comment] 2015-10-12 07:53
No, I don't think I tested it. But mismatching braces are obviously incorrect, so even if they seem to work, I have a strong feeling that there's still a bug somewhere and we're just adapting our software to that bug.

**Comment by Udera** [comment] 2015-10-12 08:20
Yes, there is something wrong. But I'm not expert enough to tell where the bug is. I only tried to make it work that I can continue to implement the rewrite-subject options.

**Comment by Z3po** [comment] 2015-10-13 18:54
The Problem here is neither a missing colon nor missing brackets.

According to https://bugs.exim.org/show_bug.cgi?id=1533 when implementing https://bugs.exim.org/show_bug.cgi?id=337 they backwards-broke nested conditions in headers_add/headers_remove statements.

You may try the following branch version (I took the current trunk/master and just divided the nested conditions into different headers_remove statements):
https://github.com/Z3po/vexim2/tree/issue#81

**Comment by Z3po** [comment] 2015-10-13 18:58
I'm a bit confused you got it fixed by just adding a extra bracket...did you check the statements still work like expected?

* removing X-Spam-Score and X-Spam-Report headers when spam_score less than 10
* removing X-Spam-Score and X-Spam-Report headers when spam_score less than sa_tag value times 10
* removing X-Spam-Score and X-Spam-Report headers when sa_tag value times 10 equals 0

**Comment by Udera** [comment] 2015-10-13 21:21
I only tested with spam and normal mail if the headers are removed. I didn't check with spam-points in intervals [0,1] and [1, sa_tag*10].

The problem with the current configuration is, it doesn't work in exim <4.83, =4.84 (debian 8, should include bugfix #1533), or 4.86 (debian testing).

I didn't test your version yet.

**Comment by Z3po** [comment] 2015-10-14 20:29
So that's the problem...looks like they broke compatibility to older versions behavior. I'm not sure how we deal with that. Supplying different configfiles or creating a beast of a sql statement (if possible at all) so we're not having multiple conditions. I'm not happy with either but probably we need different configfiles here. Would help us with other feature implementations coming in newer versions as well.

**Comment by Z3po** [comment] 2015-10-14 20:30
Just to clarify: bug #1533 doesn't give any fixes but implements better logging of errors. They state there that this is expected behavior.

**Comment by Udera** [comment] 2015-10-14 22:36
Even if I take only the `headers_remove` from your fix (https://github.com/Z3po/vexim2/blob/b49a3c5f90f48efb06b24881dfbda3e19af24e4e/docs/configure#L666-L670) I get this error:
````
 6184   message: virtual_domains router failed to expand "${if <{$spam_score_int}{${lookup mysql{select users.sa_tag * 10 from users,domains where localpart = '${quote_mysql::$local_part}' and domain = '${quote_mysql::$domain}' and users.on_spamassassin = 1 and users.domain_id=domains.domain_id}{$value}fail}} {X-Spam-Score:X-Spam-Report}}": missing } at end of string
 6184 ----------- end verify ------------
````

**Comment by Udera** [comment] 2015-10-14 23:11
Really really strange. Now I tried this:
````
headers_remove = ${if <{$spam_score_int}{30} {X-Spam-Report:X-Spam-Score}}
````
It fails:
````
virtual_domains router failed to expand "${if <{$spam_score_int}{30} {X-Spam-Report:X-Spam-Score}}": missing } at end of string
````
This on the other hand:
````
 headers_remove = ${if <{$spam_score_int}{30} {X-Spam-Report}}
````
works, but only removes the X-Spam-Report. it's too late to think clearly.

**Comment by rimas-kudelis** [comment] 2015-10-15 06:22
@Z3po from looking at these bugs again, at @Udera's comment and at b49a3c5f90f48efb06b24881dfbda3e19af24e4e, I guess your fix won't work either. If I understand the problem correctly, we can have as many conditions as we want in our headers_remove statement, but we can only specify one header for each of these conditions (so that the string can be split by colons and each resulting item expanded separately). I think what would perhaps work is if we duplicated our current `headers_remove` statement, but specified only one header to be removed in each of these duplicates. If you're willing to test, it would be something like this:
```
  headers_remove = ${if or { { <{$spam_score_int}{1} } \
  			     { <{$spam_score_int}{${lookup mysql{select users.sa_tag * 10 from users,domains \
			       where localpart = '${quote_mysql::$local_part}' \
			       and domain = '${quote_mysql::$domain}' \
			       and users.on_spamassassin = 1 \
			       and users.domain_id=domains.domain_id}{$value}fail}} } \
			     { eq {0}{${lookup mysql{select users.sa_tag * 10 from users,domains \
			       where localpart = '${quote_mysql::$local_part}' \
			       and domain = '${quote_mysql::$domain}' \
			       and users.on_spamassassin = 0 \
			       and users.domain_id=domains.domain_id}{$value}fail}}} \
			   } {X-Spam-Score} }
  headers_remove = ${if or { { <{$spam_score_int}{1} } \
  			     { <{$spam_score_int}{${lookup mysql{select users.sa_tag * 10 from users,domains \
			       where localpart = '${quote_mysql::$local_part}' \
			       and domain = '${quote_mysql::$domain}' \
			       and users.on_spamassassin = 1 \
			       and users.domain_id=domains.domain_id}{$value}fail}} } \
			     { eq {0}{${lookup mysql{select users.sa_tag * 10 from users,domains \
			       where localpart = '${quote_mysql::$local_part}' \
			       and domain = '${quote_mysql::$domain}' \
			       and users.on_spamassassin = 0 \
			       and users.domain_id=domains.domain_id}{$value}fail}}} \
			   } {X-Spam-Report} }
```

If that works, the only problem is now the duplication of this enormous condition. To avoid that, perhaps we could define a variable/macro/whatever using our current condition, and then remove each of the headers based on that macro?

**Comment by Udera** [comment] 2015-10-15 08:45
I tried this configuration:
````
    headers_remove = ${if or { { <{$spam_score_int}{1} } \
                             { <{$spam_score_int}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                               where localpart = '${quote_mysql::$local_part}' \
                               and domain = '${quote_mysql::$domain}' \
                               and users.on_spamassassin = 1 \
                               and users.domain_id=domains.domain_id}{$value}fail}} } \
                             { eq {0}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                               where localpart = '${quote_mysql::$local_part}' \
                               and domain = '${quote_mysql::$domain}' \
                               and users.on_spamassassin = 0 \
                               and users.domain_id=domains.domain_id}{$value}fail}}} \
                           } {X-Spam-Report} }
````
and it looks good. So I updated the pull request https://github.com/vexim/vexim2/pull/82.

Only verified on Debian Jessie 8. Is this compatible with Exim <4.83?

**Comment by rimas-kudelis** [comment] 2015-10-15 08:48
You forgot the `X-Spam-Score` header.

**Comment by Udera** [comment] 2015-10-15 08:57
> You forgot the X-Spam-Score header.

I first tested only one `headers_remove`. I retested with the pull request: https://github.com/vexim/vexim2/pull/82#issuecomment-148322041

**Comment by rimas-kudelis** [comment] 2015-10-15 09:13
Is it possible to turn the query or its result into a variable/macro and use that instead of specifying the query twice?

**Comment by Udera** [comment] 2015-10-15 10:50
I don't know. I tried two different ideas. Some suggest to use double-colons
````
{X-Spam-Score::X-Spam-Report}
````
This doesn't produce an error, in the debug mode I see that the database query returns the result `20`, but the headers are not remove (score: 1.1).

Other option is to change the list separators (http://www.exim.org/exim-html-current/doc/html/spec_html/ch-the_exim_run_time_configuration_file.html#SECTlistsepchange), I tried the semicolon:
````
  headers_remove = <; ${if or { { <{$spam_score_int}{1} } \
                             { <{$spam_score_int}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                               where localpart = '${quote_mysql::$local_part}' \
                               and domain = '${quote_mysql::$domain}' \
                               and users.on_spamassassin = 1 \
                               and users.domain_id=domains.domain_id}{$value}fail}} } \
                             { eq {0}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                               where localpart = '${quote_mysql::$local_part}' \
                               and domain = '${quote_mysql::$domain}' \
                               and users.on_spamassassin = 0 \
                               and users.domain_id=domains.domain_id}{$value}fail}}} \
                           }  {X-Spam-Score;X-Spam-Report}}
````
No errors. But headers are not removed either.

Even this won't work:
````
headers_remove = <; X-Spam-Report;X-Spam-Score
````
or
````
headers_remove = <; X-Spam-Report ; X-Spam-Score
````
or
````
headers_remove = <; X-Spam-Report: ; X-Spam-Score:
````

So already thought my system is perhaps broken, but using this line instead is working (headers are removed):
````
headers_remove = X-Spam-Report:X-Spam-Score
````

Any ideas?

**Comment by Udera** [comment] 2015-10-15 10:55
And this should be possible in the headers_remove
>Warning 3: Because of the separate expansion of the list items, items that contain a list separator must have it doubled. To avoid this, change the list separator (6.20).

http://www.exim.org/exim-html-current/doc/html/spec_html/ch-generic_options_for_routers.html

**Comment by rimas-kudelis** [comment] 2015-10-15 14:55
No, that's not what I meant. From my understanding, whether or not you change the list separator, each header name will still have to be expanded separately.
What I meant is, perhaps we could define a macro (or a variable, I can't see a difference between them really), where we would put the result of our huge condition, and then use that macro as a condition in multiple `headers_remove` lines, or as a precondition for a single `headers_remove` line (similarly to `ifdef`). Something like this:
```
remove_headers_condition = or { { <{$spam_score_int}{1} } \
                 { <{$spam_score_int}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                   where localpart = '${quote_mysql::$local_part}' \
                   and domain = '${quote_mysql::$domain}' \
                   and users.on_spamassassin = 1 \
                   and users.domain_id=domains.domain_id}{$value}fail}} } \
                 { eq {0}{${lookup mysql{select users.sa_tag * 10 from users,domains \
                   where localpart = '${quote_mysql::$local_part}' \
                   and domain = '${quote_mysql::$domain}' \
                   and users.on_spamassassin = 0 \
                   and users.domain_id=domains.domain_id}{$value}fail}}} \
               }
```
And then either this:
```
remove_headers = ${if remove_headers_condition {X-Spam-Report}}
remove_headers = ${if remove_headers_condition {X-Spam-Score}}
```
or this:
```
IF remove_headers_condition
remove_headers = X-Spam-Report:X-Spam-Score
ENDIF
```
Is any of this possible?

**Comment by Udera** [comment] 2015-10-15 15:50
Sorry, I ignored your idea. I just tried to add a customized variable in the router section. But exim refuses to start (like your `remove_headers_condition`, also capital letters).

But `address_data`-variable seems to be promising: http://www.exim.org/exim-html-current/doc/html/spec_html/ch-generic_options_for_routers.html

**Comment by Z3po** [comment] 2015-10-15 20:18
I'm not sure if that makes sence but can you try:

X-Spam-Report::X-Spam-Score:

?

**Comment by Z3po** [comment] 2015-10-15 20:57
Or...and hopefully that doesn't work:

X-Spam-Report:::X-Spam-Score:

**Comment by Udera** [comment] 2015-10-16 07:26
I continued with the `address_data`-field. Now I only need to run one mysql query.
What do you think? @rimas-kudelis, @Z3po
https://github.com/Udera/vexim2/commit/75fc14e495be6382ec84af2402b8f13647601db8

**Comment by rimas-kudelis** [comment] 2015-10-16 19:02
@Z3po: from my understanding, no matter how many colons you use, the string will not be split once again after expanding, so if you use X-Spam-Report::X-Spam-Score, it will just look for a SINGLE header with that name with one colon, which it will obviously not find. And with three colons I guess you'd get an expansion error again.

@Udera: your way seems quite clean. Have you tested if it works? I only have one note to that: I don't see why you wanted to rename `on_spamassassin` to `on_sa` when `SELECT`'ing. In my opinion, the name should probably stay as it is.

**Comment by Udera** [comment] 2015-10-16 20:33
@rimas-kudelis It worked for me on Debian Jessie. But I didn't check all the conditions (like forwarding etc.). Would be good if someone else can test it.

Renaming was not done on purpose. I corrected it and also put the changes in the debian-files.

**Comment by Z3po** [comment] 2015-10-17 13:08
Yeah..i like using the address_data field.
I tried a different approach that wouldn't break any version exim:

https://github.com/Z3po/vexim2/tree/issue%2381

we can just add headers if needed then we don't have to "remove" them.
just let me know what you mean....

**Comment by Udera** [comment] 2015-10-17 20:24
We can even use this in the transport-router: https://github.com/Udera/vexim2/commit/1f263f13ea2e78115cf39b8fe5a4d2e90a38f900

@Z3po Did you test your changes?

**Comment by Z3po** [comment] 2015-10-17 20:28
I did. Not exactly in that version but with my running config in the exactly same way.
I like how the address_data lookup cleans up everything. Definitely our way to go.

BTW I testes on debian wheezy. Can you try on Debian Jessi? Will setup testmachines myself but haven't yet...

**Comment by Udera** [comment] 2015-10-17 21:52
I haven't tried yet. There is a test protocol (to test other things as well):
https://github.com/vexim/vexim2/blob/master/docs/checklist.txt

It a little bit old and outdated, but in general it's a very good idea to go through. This way we should install vexim on different systems and verify it works. What systems are needed?
Debian Wheezy/Jessie, FreeBSD, CentOS?

**Comment by rimas-kudelis** [comment] 2015-10-18 13:16
> We can even use this in the transport-router: Udera@1f263f1

If that works, this is awesome!!!

**Comment by Udera** [comment] 2015-10-18 19:59
> > We can even use this in the transport-router: Udera@1f263f1
> 
> If that works, this is awesome!!!
It works on Debian Jessie. This `address_data` is an old feature, so there should be no problem with backward compatibility.

**Comment by Z3po** [comment] 2015-10-18 20:16
Any feedback to headers_add instead of headers_remove? The way we'd like to go? Or not?

**Comment by Udera** [comment] 2015-10-29 07:50
@Z3po : There is a little problem with alias-addresses: Forwarded mails as well as mail for the mailbox pass use the `virtual_domains`-router. If you set an alias address alias1@example.org which is forwarded to user@example.org, this mail passes the  `virtual_domains`-router twice. In that case, you get all the spam-headers added twice! In the current setup this is true for the `X-Spam-Flag`.

I don't know if it is possible to add a header only if there isn't already this type of header. And in that case we needed to remove all `X-Spam-*`-headers from other mailservers first.

**Closed** 2015-11-01 19:05 UTC
